### ISSUE TITLE
Cannot build assertj-jide

### ISSUE THREAD

**Issue by levsa** [joel-costigliola/assertj-swing#193]
Cannot seem to build assertj-swing completely, getting the error:

Failed to execute goal on project assertj-swing-jide: Could not resolve dependencies for project org.assertj:assertj-swing-jide:jar:3.4.1-SNAPSHOT: The following artifacts could not be resolved: com.jidesoft:jide-common:jar:3.6.14, com.jidesoft:jide-grids:jar:3.6.14, com.jidesoft:jide-action:jar:3.6.14, com.jidesoft:jide-components:jar:3.6.14, com.jidesoft:jide-dock:jar:3.6.14, com.jidesoft:jide-editor:jar:3.6.14, com.jidesoft:jide-shortcut:jar:3.6.14: Failure to find com.jidesoft:jide-common:jar:3.6.14 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by croesch** [comment]
Hi thanks for providing the feedback! Since [JIDE](http://jidesoft.com/) is not open source I think the best case is to disable automatic building of the AssertJ Swing JIDE with the rest of AssertJ Swing.

Currently I download the development version of JIDE every time, integrate it and then release AssertJ Swing. But yes.That's not a really open solution :)

**Comment by croesch** [comment]
Done

**Comment by levsa** [comment]
Thanks for the fix!
