### ISSUE TITLE
How to transfer jvm-specific  arguments to the applicationLauncher？

### ISSUE THREAD

**Issue by zenddup** [joel-costigliola/assertj-swing#221]
Hi,
Our application is a complicate script with many arguments,I don't know how to put all these arguments to  applicationLauncher method???

-------------------the startup script begin---------------------------------------------------------------
javaw.exe -Dfile.encoding="GBK" -classpath .\plugins\com.galaxy.framework.iview -Xdebug -XX:+TieredCompilation -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=40 -Xverify:none -Dparsertype=2 -Xms512m -Xmx4096m -Xmn256m -XX:PermSize=128M -XX:MaxPermSize=256M -XX:+UseSerialGC -Dsun.java2d.noddraw=true -Dhelpapp=run_help.bat -XX:+HeapDumpOnOutOfMemoryError -Djava.library.path=..\lib;.\plugins\com.galaxy.gis.thirdparty\supermap_runtime com.startup.Startup

-------------------the startup script end---------------------------------------------------------------
Thank you very much.
Johnny.Z

**Comment by zenddup** [comment]
I mean how to transfer  JVM-specific arguments (e.g. -Xms, -Xmx) toapplicationLauncher method？

Thanks very much

**Comment by croesch** [comment]
I'm not sure if I understand your request correctly but just pass the arguments to your test suite. Since the AUT runs in the same JVM as the tests itself, you can pass these parameters to the test runner. How do you run your tests?

I hope that helps, I close the issue as I think the answer should be helpful, but if I'm wrong just reopen it and post additional details, thx in advance.

**Comment by zenddup** [comment]
thanks，adding the jvm parameters to the test runner works.
