### ISSUE TITLE
When will AssertJ Swing 3.11 be released?

### ISSUE THREAD

**Issue by LorenzoBettini** [joel-costigliola/assertj-swing#232]
From what I see from the repository, the current master already uses assertj-core 3.11.1, so I was wondering when assertj-swing 3.11.1 is going to be released.
Currently assertj-swing 3.8 does no allow to use assertj-core 3.11.1 because of the missing RuntimeIOException and thus, when using assertj-swing, lots of new API like noneMatch, noneSatisfy, from recent releases of assertj-code, cannot be used

**Comment by joel-costigliola** [comment]
That would be a question for @croesch ;-)

**Comment by croesch** [comment]
Thanks for asking @LorenzoBettini I did forget the release in Novembre and will release the new version this week. It will probably be 3.9.0 but I guess the version number isn't important to you ;-)

**Comment by LorenzoBettini** [comment]
Well... I would have imagined that the version number would be just the same as the assertj-core version number... why would it be different? From the latest commits I seem to understand that assertj-swing is already using assertj-core 3.11.1, or am I missing something?

**Comment by croesch** [comment]
@LorenzoBettini I just released AssertJ Swing 3.9.2 which uses assertj-core 3.11.1. Version numbers differ because release cycles are not in sync between AssertJ Swing and assertj-core.

**Comment by LorenzoBettini** [comment]
but then, just for curiosity, why you progress from 3.8.0 to 3.9.2? ;)

**Comment by croesch** [comment]
Sure ;) thanks for asking. The answer will be a bit funny but that should give you enough insight about the release process..

`3.9.0` and `3.9.1` failed and I had to fix some JavaDoc. Unfortunately I do so little work on AssertJ Swing that each time I release it, my settings have to be fixed. So that wasn't the first time I failed to release the library with the first try. And since I'm too lazy I didn't remove the failed `3.9.0` nor `3.9.1` even if both are unusable and unavailable for the public but I decided to leave the history as is - so anybody can see the funny mistakes in the history :+1:
